import os
import glob

from util.config import BUGGY_PATH, PROJECT


# This script removes files generated by the pipeline.
if __name__ == "__main__":
    if PROJECT.startswith("data_structures"):
        clean_file_name_list = ["buggy.json", "error_message.json", "buggy-embedding.pkl", "vote_results.json"]
    elif PROJECT.startswith("compiler_technology"):
        clean_file_name_list = ["buggy.json", "error_message.json", "file_line_map.json", "vote_results.json"]
    elif PROJECT.startswith("test_ds"):
        clean_file_name_list = ["buggy.json", "error_message.json", "file_line_map.json", "vote_results.json"]
    for clean_file_name in clean_file_name_list:
        for file in glob.glob(f"{BUGGY_PATH}/**/{clean_file_name}", recursive=True):
            os.remove(file)
